In [24]:
import numpy as np

np.random.seed(0)

In [34]:
class KMeans:
    def __init__(self, n_clusters, max_iter=100, verbose=1):
        self.n_clusters = n_clusters
        self.max_iter = max_iter 
        self.verbose = verbose
        
    def fit(self, X):
        # Randomly select the initial centroids from the given points (with no replacement)
        idx = np.random.choice(len(X), self.n_clusters, replace=False)
        self.centroids = X[idx]
        if self.verbose: print('Centroids:', self.centroids)
            
        # Allocate a distances matrix between the data points and the centroids
        distances = np.zeros((len(X), self.n_clusters))
            
        # Run the algorithm until convergence or max_iter has been reached
        for iteration in range(self.max_iter):        
            if self.verbose: print('\nIteration', iteration)
                
            prev_labels = None
            
            # Compute the distances to the cluster centroids
            for i in range(self.n_clusters):
                distances[:, i] = np.sum((X - self.centroids[i])**2, axis=1)
                
            # Assign each data point to the cluster with the nearest centroids
            self.labels = np.argmin(distances, axis=1) 
            if self.verbose: print('Labels:', self.labels)
            
            # Check if there was no change in the cluster assignments
            if prev_labels and np.all(self.labels == prev_labels):
                break
            prev_labels = self.labels
                
            # Recompute the centroids
            for i in range(self.n_clusters):
                self.centroids[i] = np.mean(X[self.labels == i], axis=0)
            if self.verbose: print('Centroids:', self.centroids)

In [35]:
X = np.array([[0, 1], [1, 4], [1, 9], [2, 2], [2, 7], [3, 8], [4, 7], [5, 3], [6, 4], [7, 3]], dtype=float)

In [36]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(X)

Centroids: [[4. 7.]
 [1. 4.]
 [7. 3.]]

Iteration 0
Labels: [1 1 0 1 0 0 0 2 2 2]
Centroids: [[2.5        7.75      ]
 [1.         2.33333333]
 [6.         3.33333333]]

Iteration 1
Labels: [1 1 0 1 0 0 0 2 2 2]
Centroids: [[2.5        7.75      ]
 [1.         2.33333333]
 [6.         3.33333333]]

Iteration 2
Labels: [1 1 0 1 0 0 0 2 2 2]
Centroids: [[2.5        7.75      ]
 [1.         2.33333333]
 [6.         3.33333333]]

Iteration 3
Labels: [1 1 0 1 0 0 0 2 2 2]
Centroids: [[2.5        7.75      ]
 [1.         2.33333333]
 [6.         3.33333333]]

Iteration 4
Labels: [1 1 0 1 0 0 0 2 2 2]
Centroids: [[2.5        7.75      ]
 [1.         2.33333333]
 [6.         3.33333333]]

Iteration 5
Labels: [1 1 0 1 0 0 0 2 2 2]
Centroids: [[2.5        7.75      ]
 [1.         2.33333333]
 [6.         3.33333333]]

Iteration 6
Labels: [1 1 0 1 0 0 0 2 2 2]
Centroids: [[2.5        7.75      ]
 [1.         2.33333333]
 [6.         3.33333333]]

Iteration 7
Labels: [1 1 0 1 0 0 0 2 2 2]
Centroid

In [5]:
# bad random seed 3
# (array([2, 2, 1, 2, 1, 0, 0, 2, 2, 2], dtype=int64),
#  array([[3.5       , 7.5       ],
#         [1.5       , 8.        ],
#         [3.5       , 2.83333333]]))

# bad random seed 5
# (array([0, 1, 2, 0, 1, 1, 1, 0, 0, 0], dtype=int64),
#  array([[4. , 2.6],
#         [2.5, 6.5],
#         [1. , 9. ]]))