In [20]:
# Author: Roi Yehoshua <roiyeho@gmail.com>
# License: MIT

import numpy as np

1. Loading the data set

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

In [3]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
df = load_iris(as_frame=True).data
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

2. Train-Test Split

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [6]:
X_train.shape

(112, 4)

In [7]:
X_test.shape

(38, 4)

3. Data preprocessing

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [10]:
X_train[:5]

array([[ 0.01543995, -0.11925475,  0.22512685,  0.35579762],
       [-0.09984503, -1.04039491,  0.11355956, -0.02984109],
       [ 1.05300481, -0.11925475,  0.95031423,  1.12707506],
       [-1.36797986,  0.34131533, -1.39259884, -1.31530348],
       [ 1.1682898 ,  0.11103029,  0.72717965,  1.38416753]])

4. Choose a model

In [11]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

5. Train the model

In [12]:
clf.fit(X_train, y_train)

LogisticRegression()

6. Evaluate the model on the training set

In [13]:
clf.score(X_train, y_train)

0.9732142857142857

7. Transform the test set

In [14]:
X_test = scaler.transform(X_test)

8. Evalute the model on the test set

In [15]:
clf.score(X_test, y_test)

0.9736842105263158

9. Use the model for predictions.

In [22]:
new_sample = np.array([[5, 3, 1, 0.5]])
clf.predict(new_sample)

array([1])