In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([1, 0, 2])

print(A + x)

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]]


In [3]:
y = np.array([1, 2])
print(A + y)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 