In [1]:
import numpy as np

In [2]:
A = np.array([[1, 0], [0, 1], [2, 2]])

In [3]:
np.linalg.svd(A)

(array([[-2.35702260e-01,  7.07106781e-01, -6.66666667e-01],
        [-2.35702260e-01, -7.07106781e-01, -6.66666667e-01],
        [-9.42809042e-01, -1.11022302e-16,  3.33333333e-01]]),
 array([3., 1.]),
 array([[-0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]]))

Truncated SVD

In [4]:
U, S, Vt = np.linalg.svd(A)

k = 1  # target rank
U_k = U[:, :k]
S_k = np.diag(S[:k])
Vt_k = Vt[:k, :]

A_k = U_k @ S_k @ Vt_k
A_k

array([[0.5, 0.5],
       [0.5, 0.5],
       [2. , 2. ]])

Dimensionality reduction

In [5]:
V_k = Vt.T[:, :k]

A @ V_k

array([[-0.70710678],
       [-0.70710678],
       [-2.82842712]])

In [6]:
U_k @ S_k

array([[-0.70710678],
       [-0.70710678],
       [-2.82842712]])

In [7]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=1, random_state=0)
A_reduced = svd.fit_transform(A)
A_reduced

array([[0.70710678],
       [0.70710678],
       [2.82842712]])