In [1]:
import numpy as np

Q1. Given an array A, print all the numbers that appear more than twice in the array.

In [8]:
A = np.array([1, 2, 2, 3, 3, 4, 1, 3, 1])

In [9]:
values, counts = np.unique(A, return_counts=True)
values[counts > 2]

array([1, 3])

Q2. Given an array A and a number v, find the closest value in A to v.

In [12]:
A = np.array([10, 3, 7, 8, 15])
v = 4

In [13]:
A[np.argmin(np.abs(A - v))]

3

Q3. Given a matrix A, print the number of rows in the matrix that contain the number 5.

In [14]:
A = np.array([[1, 5, 8], [2, 3, 4], [5, 9, 0]])

In [15]:
np.count_nonzero(np.any(A == 5, axis=1))

2

Q4. Given a matrix A, print the indices of the columns that contain a number greater than 7.

In [16]:
A = np.array([[1, 2, 8], [3, 4, 1], [10, 5, 5]])

In [18]:
np.where(np.any(A > 7, axis=0))[0]

array([0, 2], dtype=int64)

Q5. Given a matrix A, nor|malize its rows such that the numbers in each row sum to 1.

In [21]:
A = np.array([[1, 2, 1], [1, 4, 5]])

In [20]:
A = A / np.sum(A, axis=1).reshape(-1, 1) # broadcast an array of shape (m, n) with a column vector (m, 1)
A

array([[0.25, 0.5 , 0.25],
       [0.1 , 0.4 , 0.5 ]])

Q6. Given a matrix A, zero out all the rows that contain a negative number.

In [27]:
A = np.array([[-1, 2, 1], [1, 4, 5]])

In [28]:
A[np.where(np.any(A < 0, axis=1))] = np.zeros(A.shape[1])
A

array([[0, 0, 0],
       [1, 4, 5]])

Q7. Given an array A, find all the even numbers in the array that are followed by an odd number.

In [30]:
A = np.array([4, 2, 7, 11, 8, 5, 10, 14])

In [32]:
even = (A % 2 == 0)
next_odd = (np.roll(A, -1) % 2 == 1)
A[even & next_odd]

array([2, 8])

Q8. Given an array A, find all the local maxima (peaks) in the array. A local maximum is a number that is greater or equal to its two neighbors. 

In [33]:
A = np.array([5, 8, 3, 1, 10, 9, 12])

In [34]:
B = A[1:-1]  # the first and last numbers cannot be peaks
B[(B > A[:-2]) & (B > A[2:])]

array([ 8, 10])

Q9. Given a matrix A, find how many rows in A contain duplicate values.

In [36]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 8, 8]])

In [37]:
s = np.sort(A, axis=1)
np.count_nonzero(np.any(s[:, 1:] == s[:, :-1], axis=1))

2

Q10. Given a matrix A, find all the saddle points in A. An element in the matrix is a saddle point, if it is both the minimum of its row and maximum of its column or vice versa.

In [38]:
A = np.array([[9, 12, 7, 3, 12], 
              [3, 10, 6, 2, 4],
              [18, 24, 17, 6, 11],
              [15, 21, 13, 8, 12],
              [1, 18, 22, 4, 15]])

In [41]:
n1 = np.argmin(A, axis=0)
m1 = np.argmax(A, axis=1)

n2 = np.argmax(A, axis=0)
m2 = np.argmin(A, axis=1)

i = np.arange(A.shape[0])
idx1 = np.where(m1[n1[i]] == i)[0]
idx2 = np.where(m2[n2[i]] == i)[0]

saddle1 = A[idx1, n1[idx1]]
saddle2 = A[idx2, n2[idx2]]
np.hstack((saddle1, saddle2))

array([10,  8])